- name: copy dera_ops_client.tar.gz to remote host
  copy: src=dera_ops_client.tar.gz dest=/opt/dera_ops_client.tar.gz
  tags: cppkg
# 保留客户端原cert_id(客户端升级用,同时playbook下的cert.txt填写{{ cert_id }})
- name: create cert_id
  shell: cat /opt/dera_ops_client/conf/cert.txt
  register: cert
- set_fact: cert_id="{{cert.stdout}}"

#- name: sync date
#  shell: date -s {{ server_date }}
# 设置远程执行sudo
- name: set sudoers
  shell: sed -i 's/Defaults    requiretty/Defaults    !requiretty/g' /etc/sudoers

- name: tar dera_ops_client.tar.gz
  shell: cd /opt;sudo tar -xf dera_ops_client.tar.gz

- name: copy cert.txt
  template: src=cert.txt dest=/opt/dera_ops_client/conf/cert.txt

- name: copy run_client.sh
  copy: src=run_client.sh dest=/opt/dera_ops_client/run_client.sh

#- name: install pkg
#  shell: easy_install pip;python /opt/dera_ops_client/setup.py

- name: restart client
  shell: sh /opt/dera_ops_client/run_client.sh stop;sh /opt/dera_ops_client/run_client.sh start

#设置开机启动(第一次安装用)
#- name: set reboot
#  shell: sed -i '$a\sh /opt/dera_ops_client/run_client.sh start' /etc/rc.d/rc.local;chmod +x /etc/rc.d/rc.local
- name: enable client
  shell: sh /opt/dera_ops_client/run_client.sh enable