- name: copy ops_client.tar.gz to remote host
  copy: src=ops_client.tar.gz dest=/usr/local/src/ops_client.tar.gz
  tags: cppkg

- name: create cert_id
  shell: cat /usr/local/src/ops_client/conf/cert.txt
  register: cert
- set_fact: cert_id="{{cert.stdout}}"

- name: tar ops_client.tar.gz
  shell: cd /usr/local/src;tar -xf ops_client.tar.gz

- name: copy cert.txt
  template: src=cert.txt dest=/usr/local/src/ops_client/conf/cert.txt

- name: copy run_client.sh
  copy: src=/opt/run_client.sh dest=/opt/run_client.sh

- name: restart client
  shell: sh /opt/run_client.sh stop;sh /opt/run_client.sh start